### ISSUE TITLE
Does not work with Cloudkey Firmware Version 2.X

### ISSUE THREAD

**Issue by rroach3753** [bacherd/MMM-UniFi-Voucher#1]
UI has made major upgrades in the 2.X FW.  The /api/login page is not found, nor is the /api.  Will you be creating a version for UnifiOS (FW v2.X)?

Looks like the URL to the new hotspot manager isn't using 8443 either.  It's "URL/network/hotspot-manager/site/default/vouchers/1/50" to see the vouchers when logged in.

**Comment by bacherd** [comment]
I use the Docker container jacobalberty / unifi: stable-6 as a controller and don't have a UniFI Cloudkey. So I can't find out and test the new API.

Maybe it is enough if you change the URL in the config to the new port?

"URL/network/hotspot-manager/site/default/vouchers/1/50" is the URL to the vouchers page but I need the URL to the API.

![screenshot-2021 08 04-09 20](https://user-images.githubusercontent.com/48548669/113985859-e6ad8500-984c-11eb-9cc2-74d3e7ebb168.png)

**Comment by rroach3753** [comment]
> I use the Docker container jacobalberty / unifi: stable-6 as a controller and don't have a UniFI Cloudkey. So I can't find out and test the new API.
> 
> Maybe it is enough if you change the URL in the config to the new port?
> 
> "URL/network/hotspot-manager/site/default/vouchers/1/50" is the URL to the vouchers page but I need the URL to the API.
> 
> ![screenshot-2021 08 04-09 20](https://user-images.githubusercontent.com/48548669/113985859-e6ad8500-984c-11eb-9cc2-74d3e7ebb168.png)

OK, cool.  Here's what I found in the Gen2+ FW 2.X
![2021-04-08_11-08-00](https://user-images.githubusercontent.com/74986787/114051230-e7e5ae80-985a-11eb-811e-4cd243ba1378.png)

**Comment by bacherd** [comment]
Can you change your url to everything befor /api

```
{
    module: "MMM-UniFi-Voucher",
    position: "right",
    header: "hotspot",
    config: {
        user: "mirror",
        pwd: "xxxxxxxxxx",
        url: "https://unifi-controller:8443/proxy/network",
    }
},
```

**Comment by rroach3753** [comment]
Let me give it a shot.

**Comment by rroach3753** [comment]
That doesn't resolve it either.  I will say that the only URL that uses 8443 is the captive portal URL.  When I go to the Vouchers page or anywhere in the hotspot manager, it uses HTTPS on 443.

**Comment by rroach3753** [comment]
OK.  If I go to https://URL/proxy/network/api/login (no port 8443 because this returns no page at all) I get this message in the browser: {"meta":{"rc":"error","msg":"api.err.NoSiteContext"},"data":[]}

**Comment by bacherd** [comment]
Have you tried it with ```url:"https://unifi-controller:443/proxy/network"```

I use ```url:"https://192.168.8.1:8443``` and have the same response on ```https://192.168.8.1:8443/api/login```

**Comment by rroach3753** [comment]
When it comes to HTTPS it defaults to 443 so that shouldn't have to be specified.  I have tried it with and without :443 to no avail.   I'm wondering what other underlying changes UI has made that is causing the issue.  I can tell you that my MM still works without issue (as you know incorrect code can cause MM to fail to start or start blank; I'm not having either issue).  I see the block on my MM for my Hotspot Vouchers, it just doesn't connect to pull the vouchers.

**Comment by rroach3753** [comment]
Now at URL/proxy/network/api/login I'm getting an "Unauthorized" message on the page...different than the previous error.

EDIT: This "unauth" error is because I was logged out of the controller.  The same previous message exists when I'm logged into the controller.

**Comment by bacherd** [comment]
Can you open your MM page on normal browser to see the console error messages?

I think it's a problem with the login. I can build a version with more debugging for you.

**Comment by rroach3753** [comment]
If you want to!  I know in the v2.X firmware they've made a ton of changes.  But they've also made a ton of changes to the Network Controller (I'm running 6.2.13 which is BETA; this could be part of the issue).  I do have a Gen 1 cloud key that I can kick up and run the stable GA release of the controller (6.0.X) to test it out on, but won't be able to get to that till the weekend.

**Comment by rroach3753** [comment]
OK, I dug out my Gen1 Cloud Key and have it updated to 1.1.19 (stable FW) and 6.1.71 (stable...lol...controller).
I have configured the Vouchers setup in the network controller, created an operator, and updated my URL to point to the IP:8443.  Soon as I did that and restarted MM the vouchers pull up with no issue. 

To the problem does appear to be with changes they've made in either the 6.2.X line of the contoller or the UnifiOS that the Cloud Key v2.X firmware based on.  Or a combination of both.

**Comment by ghost** [comment]
Actually this would be helpful to get this module to work with the never Cloud Key G2 firmware and controller 6.5.xx.
Pointing the config to the url:"https://unifi-controller:443/proxy/network" and log repeats:
[07.02.2022 08:39.58.391] [LOG]   [UniFi-Voucher] login /api/login
[07.02.2022 08:39.58.416] [LOG]   [UniFi-Voucher] null
above suggests that the login event is not handled well, despite admin credentials being used in the config.
Is a version with and extended debugging still on the table?
Regards,

**Comment by bacherd** [comment]
I switched logging to the Magic Mirror mechanism. The response and the cookie are now output via the logLevel debug.

`logLevel: ["DEBUG", "INFO", "LOG", "WARN", "ERROR"],`

This works for me with UniFi Controller Version 6.5.55 (docker [jacobalberty/unifi:v6](https://hub.docker.com/r/jacobalberty/unifi)).

I suspect it's a problem with the cookie and the "remember":true" parameter.

**Comment by ghost** [comment]
This is very helpful indeed. Thank you.
The G2 key seems to have further differences and the clue is in the [UniFi-API-client](https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php) lines 176-179:
```
        if ($http_code === 200) {
            $this->is_unifi_os         = true;
            $curl_options[CURLOPT_URL] = $this->baseurl . '/api/auth/login';
        }
```
Clearly the unifi_os is another breed altogether - after making changes in node_helper.js:
```
method: 'GET',
--url: this.config.url + '/api/s/default/stat/voucher',
++url: this.config.url + '/proxy/network/api/s/default/stat/voucher',
headers: {
```
and
```
method: 'POST',
--url: this.config.url + '/api/login',
++url: this.config.url + '/api/auth/login',
headers: {
```
with default config - all works as expected.
![Screenshot from 2022-02-15 17-50-31](https://user-images.githubusercontent.com/99172470/154119930-c6ea70bb-c335-49fe-98ef-e89bb38ed0e6.png)
Perhaps additional parameter in config like isG2 = true,false with additional if->then logic would make the module more versatile.
Regards

**Comment by bacherd** [comment]
Hi, I committed a new version with a config parameter isGen2. @ly5y can you test it for me?

@ly5y In your screenshot you have different vouchers and they have names. Is this a new feature or did you add more patches to the module?

**Comment by rroach3753** [comment]
It was working after I made the updates to the GET and POST URLs and now after your update it's broken again.

**Comment by bacherd** [comment]
@rroach3753  have you add the config parameter isGen2?

```
{
    module: "MMM-UniFi-Voucher",
    position: "right",
    header: "hotspot",
    config: {
        user: "mirror",
        pwd: "xxxxxxxxxx",
        url: "https://unifi-controller:8443/proxy/network",
        isGen2: true,
    }
},
```

**Comment by rroach3753** [comment]
Shite.  I missed that!  Let me go back and do that.  My bad!

**Comment by rroach3753** [comment]
OK, good to go.  I'm curious too, @ly5y, about the names!

**Comment by ghost** [comment]
@bacherd - Thank you - works as a charm.
In my setup I am using "Notes" field in the Hotspot Manager when creating a voucher. Changes in the MMM-UniFi-Voucher.js that makes the voucher code easier to read and bring the notes entry over:
```
item.classList.add("MMM-UniFi-Voucher");
--item.innerHTML = this.data.vouchers[index].code
++item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5) + " - "+ this.data.vouchers[index].note
list.appendChild(item)
```
Above has one flaw - if notes field is empty - the unaesthetic dash remains. Some test on on "notes" field `if is not null` then `item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5) + " - "+ this.data.vouchers[index].note` else `item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5)`
My personal preference is to have "dimming effect" css therefore my MMM-UniFi-Voucher.css is modified:
```
.MMM-UniFi-Voucher div {
	color: #999;
	font-size: 24px;
}
.MMM-UniFi-Voucher ul {
	color: #999;
	margin: 0px;
	list-style-type:none;
}
.MMM-UniFi-Voucher li:first-child {
        color: #FEFEFE;
        height: 32px;
}
.MMM-UniFi-Voucher li:nth-child(2) {
        color: #DDD;
        height: 30px;
}
.MMM-UniFi-Voucher li:nth-child(3) {
        color: #BBB;
        height: 28px;
}
.MMM-UniFi-Voucher li {
	color: #999;
	height: 26px;
}
```

Regards

**Comment by bacherd** [comment]
@ly5y thanks for finding the differences in the api.

Great ideas I'll try to incorporate them in the next few days. At the moment you can specify how many vouchers are displayed in the config. Does the number of vouchers depend on the notes or are they sorted based on the note?

**Comment by ghost** [comment]
@rroach3753 - my config looks like:
```
		{
			module: "MMM-UniFi-Voucher",
			disabled: false,
			position: "top_left",
			header: "Wi-Fi Vouchers",
			config: {
				user: "voucher_read_only",
				pwd: "xxxxxxxxxxx",
				url: "https://unifi-key",
				maximumEntries: "4",
				updateInterval: "60000",
				animationSpeed: "2500",
//				logLevel: "DEBUG",
				logLevel: "ERROR",
				isGen2: true
			}
		},
```
Regards

**Comment by bacherd** [comment]
I creaded a new issue for this. [Show Voucher Notes](https://github.com/bacherd/MMM-UniFi-Voucher/issues/3)
