### ISSUE TITLE
Show Voucher Notes

### ISSUE THREAD

**Issue by bacherd** [bacherd/MMM-UniFi-Voucher#3]
@bacherd - Thank you - works as a charm.
In my setup I am using "Notes" field in the Hotspot Manager when creating a voucher. Changes in the MMM-UniFi-Voucher.js that makes the voucher code easier to read and bring the notes entry over:
```
item.classList.add("MMM-UniFi-Voucher");
--item.innerHTML = this.data.vouchers[index].code
++item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5) + " - "+ this.data.vouchers[index].note
list.appendChild(item)
```
Above has one flaw - if notes field is empty - the unaesthetic dash remains. Some test on on "notes" field `if is not null` then `item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5) + " - "+ this.data.vouchers[index].note` else `item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5)`
My personal preference is to have "dimming effect" css therefore my MMM-UniFi-Voucher.css is modified:
```
.MMM-UniFi-Voucher div {
	color: #999;
	font-size: 24px;
}
.MMM-UniFi-Voucher ul {
	color: #999;
	margin: 0px;
	list-style-type:none;
}
.MMM-UniFi-Voucher li:first-child {
        color: #FEFEFE;
        height: 32px;
}
.MMM-UniFi-Voucher li:nth-child(2) {
        color: #DDD;
        height: 30px;
}
.MMM-UniFi-Voucher li:nth-child(3) {
        color: #BBB;
        height: 28px;
}
.MMM-UniFi-Voucher li {
	color: #999;
	height: 26px;
}
```

Regards

_Originally posted by @ly5y in https://github.com/bacherd/MMM-UniFi-Voucher/issues/1#issuecomment-1040754166_

Great ideas I'll try to incorporate them in the next few days. At the moment you can specify how many vouchers are displayed in the config. Does the number of vouchers depend on the notes or are they sorted based on the note?

**Comment by ghost** [comment]
@bacherd - The number of vouchers are determined by maximumEntries in config. Vouchers without notes:
![Screenshot from 2022-02-15 20-35-29](https://user-images.githubusercontent.com/99172470/154144850-87ca4f8c-46d4-4e0b-981a-fa299e2df4df.png)
I find `- null` quite disturbing.
Regards

**Comment by ghost** [comment]
The `- null` was really bugging me - there is another option to evaluate - when creating a voucher using Hotspot Manager the "Expiration time" drop-down list or "User-defined" is required and exposed via api as "duration". Perhaps this may be a bit lazy approach - not requiring manually add "notes" as initially demonstrated. I was playing with the getDom function a bit:
```
			if (this.data.vouchers[index].status_expires == 0 && index < this.config.maximumEntries) {
++                                duration = this.data.vouchers[index].duration;
++                                var d = Math.floor(duration / (60*24));
++                                var h = Math.floor(duration % (60*24) / 60);
++                                var m = Math.floor(duration % 60 / 1);
++                                var dDuration = d > 0 ? d + (d == 1 ? " day " : " days ") : "";
++                                var hDuration = h > 0 ? h + (h == 1 ? " hour " : " hours ") : "";
++                                var mDuration = m > 0 ? m + (m == 1 ? " minute " : " minutes ") : "";
				var item = document.createElement("li")
				item.classList.add("MMM-UniFi-Voucher");
--				item.innerHTML = this.data.vouchers[index].code
++				item.innerHTML = this.data.vouchers[index].code.substr(0,5) + "-" + this.data.vouchers[index].code.substr(-5) + Array(5).fill("\xa0").join("") +  dDuration + hDuration + mDuration;
				list.appendChild(item)
```
Duration is stored as minutes and needed conversion to a meaningful format, whereas `Array(5).fill("\xa0").join("")` populates five white-spaces (controlled by Array(num)).
![Screenshot from 2022-02-16 07-02-50](https://user-images.githubusercontent.com/99172470/154213254-e9ccd2b4-4f3b-44ea-ad49-f89f8dda022c.png)
Something to consider.
Regards

**Comment by bacherd** [comment]
I think it would make sense to have 3 new parameters in the config.

- showExpiresTime
- showNotes
- groupByNotes

groupByNotes changes the max count behavior and shows a maximum number of vouchers with the same note. And the vouchers will be sorted by the note. Vouchers without a note will show an empty placeholder.

**Comment by bacherd** [comment]
I added configurations parameters **split** and **showDurationTime**. 

@ly5y I have not used `Array(5).fill("\xa0").join("")` you can change the space now with css.

**Comment by rroach3753** [comment]
outside of the update, nothing has changed on my end and I'm no longer able to pull in vouchers.

**Comment by rroach3753** [comment]
I notice that split and showDurationTime are not showing up as autocomplete options.  Not sure if this makes a difference.

**Comment by ghost** [comment]
@bacherd - I think we are on good path. There are few interesting features introduced with comit [59f68fb](https://github.com/bacherd/MMM-UniFi-Voucher/commit/59f68fb2a5d92190591635e72d2f5ca0bf51bac4): MMM-UniFi-Voucher.js:
**Part1:** 
config: split: 0, showDurationTime: true,false
++	`var index = 0; `seems to lock first voucher:
![Screenshot from 2022-02-20 08-03-30](https://user-images.githubusercontent.com/99172470/154835657-345c7991-5335-43fe-8243-f4587fc241af.png)
changing `var index = 1; ` seems to lock second voucher (and so on):
![Screenshot from 2022-02-20 09-05-32](https://user-images.githubusercontent.com/99172470/154835683-94d82101-cfd3-450c-90a8-0439b1fa661e.png)
commenting out `// var index = 0; ` displays vouchers but only when `showDurationTime: false`
![Screenshot from 2022-02-20 09-08-03](https://user-images.githubusercontent.com/99172470/154835768-ef083af7-809d-41ff-9966-85acbb7ff10c.png)
**Part2:** 
config: split: _not zero_ , showDurationTime: false and `// var index = 0; ` bring an interesting result:
![Screenshot from 2022-02-20 09-15-00](https://user-images.githubusercontent.com/99172470/154835983-7f0f283b-21b7-4238-9db9-0ba4c734293d.png)
config: split: _not zero_  , showDurationTime: false and bringing the index back `var index = 0; ` produces nicely formatted vouchers:
![Screenshot from 2022-02-20 09-17-21](https://user-images.githubusercontent.com/99172470/154836055-73f738b5-606a-4bc1-9172-c2761e8c2e80.png)
**Part3:** 
config: split: _not zero_  , showDurationTime: true - this combination seems to have a bit of disagreement. No vouchers are shown I'm afraid:
![Screenshot from 2022-02-20 09-21-41](https://user-images.githubusercontent.com/99172470/154836177-0c7ace31-f494-4f12-84b8-16a9276f829d.png)
Regards

**Comment by bacherd** [comment]
@ly5y  thanks for the detailed bug report. I had used the index variable twice and one feature broke the other. Now it should work properly.

**Comment by bacherd** [comment]
@rroach3753 
> I notice that split and showDurationTime are not showing up as autocomplete options. Not sure if this makes a difference.

I think autocomplete option is a feature of your editor?

**Comment by ghost** [comment]
I can confirm that the module works beautifully.
The only piece I would improve is to make the configuration `split` description highlighted as number, not parameter or variable.
At first I used `spilt: "3"` with quite amusing outcome.
Regards

**Comment by ghost** [comment]
@bacherd - README.md a tiny typo
`showNote` 
--`noteFiler`    
++`noteFilter`    
Regards

**Comment by ghost** [comment]
@bacherd - regarding note filter. At the moment it compares the string.
Question: How can I bring notes like "This access point is only operating during business hours: 9:00 am to 6:00 pm; Mon to Fri"
Would be possible to extend the filter to act on keywords?
Regards

**Comment by bacherd** [comment]
> @bacherd - regarding note filter. At the moment it compares the string. Question: How can I bring notes like "This access point is only operating during business hours: 9:00 am to 6:00 pm; Mon to Fri" Would be possible to extend the filter to act on keywords? Regards

Hm maybe we could use regular expressions instead of the list. Your goal is to show different vouchers at different times or just to show similar notes.

**Comment by ghost** [comment]
@bacherd - I am thinking of showing all vouchers containing word "business" "guest" but not "toady" and "restricted".
Example:
"Business restricted vouchers for tomorrow"
"Business vouchers for tomorrow"
"Business vouchers for today"
"Guests welcome only to non-restricted"
"Guests welcome only today"
"Guests welcome only tomorrow"

With the sought logic this should return
"Business vouchers for today"
"Guests welcome only today"

It is somewhat winded example but filtering by keywords will make the module more versatile, large venues friendly
Regards

**Comment by bacherd** [comment]
I think a parameter noteFilterRegex with a regular expression like this might work? Regular expressions are a bit complicated but have a lot of possibilities.

`noteFilterRegex="^.*(Business|Guest)(?!.*(tomorrow|restricted)).*$"`

![image](https://user-images.githubusercontent.com/48548669/154845592-5dd0cbb4-f162-4d93-b8f6-4b4e112e8d9f.png)

**Comment by ghost** [comment]
@bacherd - What a great idea. noteFilter or noteFilterRegex as noteFilterType switch. This would allow for simple and complex scenarios.
Regards

**Comment by bacherd** [comment]
@ly5y I added `noteFilterRegex` is only used when `noteFilter` is empty. I used your example in the readme.

**Comment by ghost** [comment]
@bacherd - Works as a charm. I can see a great value for everyone maintaining multiple vlan driven access-points. One solution with simple and elegant filter targets multiple audiences.
Well done and great thank you.

**Comment by rroach3753** [comment]
> @rroach3753
> 
> > I notice that split and showDurationTime are not showing up as autocomplete options. Not sure if this makes a difference.
> 
> I think autocomplete option is a feature of your editor?

I use MMPM to install modules and edit the config file in the browser, so definitely possible.  Thanks!

**Comment by rroach3753** [comment]
I do have a general remark.  On Gen2 and Gen2+ devices: For the new UnifiOS, you have to create the user account in the "users" section of the UnifiOS console.  You cannot create an account in the hotspot manager any longer (except, currently, through the mobile Unifi Network App; I suspect this will go away).  Additionally, it appears that port 8443 isn't required as it uses 443 internally.  Only the captive portal page uses 8443 now.

**Comment by rroach3753** [comment]
Got updated tonight with the last round of updates tonight.  Excellent!  Thanks for this!

**Comment by ghost** [comment]
@bacherd - After updating G2 network manager to 7.0.23 all seems to be working fine. I think you can bump-up compatibility in Readme.md if you feel that tested version compatibility is needed at all.
Regards,
